maxin:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: hmdianping
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${maxin.ai.openai.api-key}
      chat:
        model: deepseek-v4-flash